In [1]:
import cv2
import tensorflow.keras as tfkeras
import tensorflow as tf
print("Available devices:", tf.config.list_physical_devices())
import keras_ocr

pipeline = keras_ocr.pipeline.Pipeline()

testFile = '/media/chowder/abhiksFiles/personalData/wyzeCams/roomCamBy3dp/20201230/10/20.mp4'

cap = cv2.VideoCapture(testFile)
frames = []
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    x1, y1 = 1350, 1000  # Starting coordinates
    x2, y2 = 1900, 1080  # Ending coordinates
    cropped_frame = frame[y1:y2, x1:x2]
    frames.append(cropped_frame)



2024-10-25 00:09:09.377353: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-25 00:09:09.381277: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-25 00:09:09.392506: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1729840149.409706 1927658 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1729840149.414923 1927658 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-25 00:09:09.435310: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

Available devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


W0000 00:00:1729840150.777083 1927658 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


Looking for /home/chowder/.keras-ocr/craft_mlt_25k.h5


ValueError: Unrecognized keyword arguments passed to Dense: {'weights': [array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32), array([1., 0., 0., 0., 1., 0.], dtype=float32)]}

In [6]:
#26 sec
prediction_groups = pipeline.recognize(frames[:60])


5/5 [==============================] - 4s 791ms/step


In [4]:
#42 sec
prediction_groups = pipeline.recognize(frames[:100])

7/7 [==============================] - 7s 939ms/step


In [ ]:
prediction_groups = pipeline.recognize(frames[:200])

In [5]:
prediction_groups

[[('20201230',
   array([[ 40.,  14.],
          [293.,  14.],
          [293.,  55.],
          [ 40.,  55.]], dtype=float32)),
  ('10119159',
   array([[318.,  14.],
          [518.,  14.],
          [518.,  57.],
          [318.,  57.]], dtype=float32))],
 [('20201230',
   array([[ 40.,  14.],
          [293.,  14.],
          [293.,  55.],
          [ 40.,  55.]], dtype=float32)),
  ('10119159',
   array([[318.,  14.],
          [518.,  14.],
          [518.,  57.],
          [318.,  57.]], dtype=float32))],
 [('20201230',
   array([[ 40.,  14.],
          [293.,  14.],
          [293.,  55.],
          [ 40.,  55.]], dtype=float32)),
  ('10120r00',
   array([[318.,  14.],
          [519.,  14.],
          [519.,  56.],
          [318.,  56.]], dtype=float32))],
 [('20201230',
   array([[ 40.,  14.],
          [293.,  14.],
          [293.,  55.],
          [ 40.,  55.]], dtype=float32)),
  ('10120600',
   array([[318.,  15.],
          [519.,  15.],
          [519.,  56.],
       

In [ ]:
for text, box in prediction_groups[0]:
    print(f"Detected text: {text}, Bounding box: {box}")

In [8]:
import tensorflow as tf
print("Available devices:", tf.config.list_physical_devices())


Available devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
