In [2]:
import cv2
import keras_ocr

pipeline = keras_ocr.pipeline.Pipeline()

testFile = '/media/chowder/abhiksFiles/personalData/wyzeCams/roomCamBy3dp/20201230/10/20.mp4'

cap = cv2.VideoCapture(testFile)
frames = []
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    x1, y1 = 1350, 1000  # Starting coordinates
    x2, y2 = 1900, 1080  # Ending coordinates
    cropped_frame = frame[y1:y2, x1:x2]
    frames.append(cropped_frame)



Looking for /home/chowder/.keras-ocr/craft_mlt_25k.h5
Looking for /home/chowder/.keras-ocr/crnn_kurapan.h5


In [6]:
#26 sec
prediction_groups = pipeline.recognize(frames[:60])


5/5 [==============================] - 4s 791ms/step


In [4]:
#42 sec
prediction_groups = pipeline.recognize(frames[:100])

7/7 [==============================] - 7s 939ms/step


In [ ]:
prediction_groups = pipeline.recognize(frames[:200])

In [5]:
prediction_groups

[[('20201230',
   array([[ 40.,  14.],
          [293.,  14.],
          [293.,  55.],
          [ 40.,  55.]], dtype=float32)),
  ('10119159',
   array([[318.,  14.],
          [518.,  14.],
          [518.,  57.],
          [318.,  57.]], dtype=float32))],
 [('20201230',
   array([[ 40.,  14.],
          [293.,  14.],
          [293.,  55.],
          [ 40.,  55.]], dtype=float32)),
  ('10119159',
   array([[318.,  14.],
          [518.,  14.],
          [518.,  57.],
          [318.,  57.]], dtype=float32))],
 [('20201230',
   array([[ 40.,  14.],
          [293.,  14.],
          [293.,  55.],
          [ 40.,  55.]], dtype=float32)),
  ('10120r00',
   array([[318.,  14.],
          [519.,  14.],
          [519.,  56.],
          [318.,  56.]], dtype=float32))],
 [('20201230',
   array([[ 40.,  14.],
          [293.,  14.],
          [293.,  55.],
          [ 40.,  55.]], dtype=float32)),
  ('10120600',
   array([[318.,  15.],
          [519.,  15.],
          [519.,  56.],
       

In [ ]:
for text, box in prediction_groups[0]:
    print(f"Detected text: {text}, Bounding box: {box}")

In [8]:
import tensorflow as tf
print("Available devices:", tf.config.list_physical_devices())


Available devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
